"""Add passive_listening_enabled to Bot model

Revision ID: 0069a27a1a6c
Revises: a181d2012660
Create Date: 2025-09-06 14:40:36.019133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0069a27a1a6c'
down_revision: Union[str, Sequence[str], None] = 'a181d2012660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('passive_listening_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'passive_listening_enabled')
    # ### end Alembic commands ###