"""Add tools_system_prompt to global_settings

Revision ID: 0a0c97e95e1b
Revises: a33303bb8252
Create Date: 2025-08-15 19:58:25.807435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0c97e95e1b'
down_revision: Union[str, Sequence[str], None] = 'a33303bb8252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column(
        'tools_system_prompt',
        sa.Text(),
        nullable=False,
        server_default=(
            "You have access to a set of tools you can use to answer the user's question.\n"
            "You must call tools by producing a JSON object with a `tool_calls` field.\n"
            "The `tool_calls` field must be a list of objects, where each object has a `function` field.\n"
            "The `function` object must have a `name` and an `arguments` field. The `arguments` field must be a JSON object with the arguments to the function.\n"
            "If you need to call a tool, you must stop generating text and produce the JSON object.\n"
            "If you don't need to call a tool, you must answer the user's question directly."
        )
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'tools_system_prompt')
    # ### end Alembic commands ###