"""Add rpc_endpoint_path to MCPServer

Revision ID: 15100589eba8
Revises: 8672cb190ff2
Create Date: 2025-09-08 19:13:45.511366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15100589eba8'
down_revision: Union[str, Sequence[str], None] = '8672cb190ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('rpc_endpoint_path', sa.String(), server_default='/mcp', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_servers', 'rpc_endpoint_path')
    # ### end Alembic commands ###
