"""Add multimodal_llm_model to global settings

Revision ID: 2d5ed58c9588
Revises: 0a0c97e95e1b
Create Date: 2025-08-20 09:32:48.484705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d5ed58c9588'
down_revision: Union[str, Sequence[str], None] = '0a0c97e95e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('multimodal_llm_model', sa.String(), nullable=False, server_default='llava'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'multimodal_llm_model')
    # ### end Alembic commands ###
