"""Make global LLM settings nullable

Revision ID: 41d1a7e40393
Revises: 702456a37312
Create Date: 2025-09-30 12:51:58.138135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d1a7e40393'
down_revision: Union[str, Sequence[str], None] = '702456a37312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema to allow NULL values in global settings."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_settings', 'decisional_llm_server_url',
                existing_type=sa.VARCHAR(),
                nullable=True)
    op.alter_column('global_settings', 'decisional_llm_model',
                existing_type=sa.VARCHAR(),
                nullable=True)
    op.alter_column('global_settings', 'decisional_llm_context_window',
                existing_type=sa.INTEGER(),
                nullable=True)
    op.alter_column('global_settings', 'tools_llm_server_url',
                existing_type=sa.VARCHAR(),
                nullable=True)
    op.alter_column('global_settings', 'tools_llm_model',
                existing_type=sa.VARCHAR(),
                nullable=True)
    op.alter_column('global_settings', 'tools_llm_context_window',
                existing_type=sa.INTEGER(),
                nullable=True)
    op.alter_column('global_settings', 'output_client_llm_server_url',
                existing_type=sa.VARCHAR(),
                nullable=True)
    op.alter_column('global_settings', 'output_client_llm_model',
                existing_type=sa.VARCHAR(),
                nullable=True)
    op.alter_column('global_settings', 'output_client_llm_context_window',
                existing_type=sa.INTEGER(),
                nullable=True)
    op.alter_column('global_settings', 'multimodal_llm_model',
                existing_type=sa.VARCHAR(),
                nullable=True)
    op.alter_column('global_settings', 'context_header_default_prompt',
                existing_type=sa.TEXT(),
                nullable=True)
    op.alter_column('global_settings', 'tools_system_prompt',
                existing_type=sa.TEXT(),
                nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema to enforce NOT NULL on global settings."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_settings', 'tools_system_prompt',
                existing_type=sa.TEXT(),
                nullable=False)
    op.alter_column('global_settings', 'context_header_default_prompt',
                existing_type=sa.TEXT(),
                nullable=False)
    op.alter_column('global_settings', 'multimodal_llm_model',
                existing_type=sa.VARCHAR(),
                nullable=False)
    op.alter_column('global_settings', 'output_client_llm_context_window',
                existing_type=sa.INTEGER(),
                nullable=False)
    op.alter_column('global_settings', 'output_client_llm_model',
                existing_type=sa.VARCHAR(),
                nullable=False)
    op.alter_column('global_settings', 'output_client_llm_server_url',
                existing_type=sa.VARCHAR(),
                nullable=False)
    op.alter_column('global_settings', 'tools_llm_context_window',
                existing_type=sa.INTEGER(),
                nullable=False)
    op.alter_column('global_settings', 'tools_llm_model',
                existing_type=sa.VARCHAR(),
                nullable=False)
    op.alter_column('global_settings', 'tools_llm_server_url',
                existing_type=sa.VARCHAR(),
                nullable=False)
    op.alter_column('global_settings', 'decisional_llm_context_window',
                existing_type=sa.INTEGER(),
                nullable=False)
    op.alter_column('global_settings', 'decisional_llm_model',
                existing_type=sa.VARCHAR(),
                nullable=False)
    op.alter_column('global_settings', 'decisional_llm_server_url',
                existing_type=sa.VARCHAR(),
                nullable=False)
    # ### end Alembic commands ###