"""Create global_settings table and add tool config to bots

Revision ID: 45bed9133b24
Revises: c7fcd512ad98
Create Date: 2025-08-11 20:03:01.050978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45bed9133b24'
down_revision: Union[str, Sequence[str], None] = 'c7fcd512ad98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ollama_host_url', sa.String(), nullable=True),
    sa.Column('context_header_default_prompt', sa.Text(), nullable=False),
    sa.Column('tool_prompts_default', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    
    # CORRECTION : Ajout de 'server_default' pour que les lignes existantes aient une valeur non-nulle.
    op.add_column('bots', sa.Column('enabled_tools', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('bots', sa.Column('context_header_override_prompt', sa.Text(), nullable=True))
    # CORRECTION : Ajout de 'server_default' pour la deuxième colonne non-nullable.
    op.add_column('bots', sa.Column('tool_prompts_overrides', sa.JSON(), server_default='{}', nullable=False))
    
    op.alter_column('bots', 'system_prompt',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bots', 'system_prompt',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('bots', 'tool_prompts_overrides')
    op.drop_column('bots', 'context_header_override_prompt')
    op.drop_column('bots', 'enabled_tools')
    op.create_table('app_settings',
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('app_settings_pkey'))
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=False)
    op.drop_table('global_settings')
    # ### end Alembic commands ###