"""Add send_file and image tools foundation

Revision ID: 45db25495b7f
Revises: 68a1e2913b5a
Create Date: 2025-08-13 19:34:03.510566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45db25495b7f'
down_revision: Union[str, Sequence[str], None] = '68a1e2913b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('image_generation_settings', sa.JSON(), nullable=True))
    op.add_column('global_settings', sa.Column('image_generation_provider', sa.String(), server_default='comfyui', nullable=True))
    op.add_column('global_settings', sa.Column('image_generation_api_url', sa.String(), server_default='http://host.docker.internal:8188', nullable=True))
    
    # --- Manual adjustment ---
    # Update the JSON content for the tool_prompts_default column
    # Alembic autogenerate cannot detect changes in JSON default values.
    op.execute("""
    UPDATE global_settings
    SET tool_prompts_default = '{
        "get_current_time": "This tool allows you to know the current date and time. You do not need to provide any arguments to it. Call this tool if the user asks you for the time, the date, or information related to the present moment.",
        "search_files": "This tool allows you to search for files stored in the system. You can search by filename, file_family (e.g., ''image'', ''text''), or owner_id (a Discord user ID). All parameters are optional. Use it when a user asks to find, list, or check for a file.",
        "analyze_file": "This tool analyzes the content of a text-based file and generates a summary. It takes one mandatory argument: ''uuid'', which is the unique identifier of the file to analyze. The summary is then stored in the file''s metadata. Use this tool when a user explicitly asks to analyze, summarize, or describe a specific file.",
        "send_file": "This tool sends a specified file to a Discord channel. It takes one mandatory argument: ''uuid'' (the unique identifier of the file). It also takes two optional arguments: ''target_user_id'' (the Discord ID of a user to mention with the file) and ''destination'' (where to send the file, which can be ''current_channel'' or ''dm'' to the target user). Use this to fulfill requests to share, post, or send a file.",
        "generate_image": "This tool generates an image based on a textual description. It takes one mandatory argument: ''prompt'', which is the detailed description of the image to create. Use this tool whenever a user asks to draw, create, or generate an image.",
        "describe_image": "This tool analyzes the content of an image file and generates a textual description of what it sees. It requires a ''uuid'' argument for the image file. Use this when the user asks what is in an image, to describe it, or to ''look'' at a picture."
    }'::jsonb
    WHERE id = 1;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- Manual adjustment ---
    # Revert the JSON content to its previous state before dropping columns.
    op.execute("""
    UPDATE global_settings
    SET tool_prompts_default = '{
        "get_current_time": "This tool allows you to know the current date and time. You do not need to provide any arguments to it. Call this tool if the user asks you for the time, the date, or information related to the present moment.",
        "search_files": "This tool allows you to search for files stored in the system. You can search by filename, file_family (e.g., ''image'', ''text''), or owner_id (a Discord user ID). All parameters are optional. Use it when a user asks to find, list, or check for a file.",
        "analyze_file": "This tool analyzes the content of a text-based file and generates a summary. It takes one mandatory argument: ''uuid'', which is the unique identifier of the file to analyze. The summary is then stored in the file''s metadata. Use this tool when a user explicitly asks to analyze, summarize, or describe a specific file."
    }'::jsonb
    WHERE id = 1;
    """)

    op.drop_column('global_settings', 'image_generation_api_url')
    op.drop_column('global_settings', 'image_generation_provider')
    op.drop_column('bots', 'image_generation_settings')
    # ### end Alembic commands ###