"""Add display_name and username to UserProfile

Revision ID: 6581499b88e4
Revises: 86e9b290086b
Create Date: 2025-08-30 22:37:46.054181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6581499b88e4'
down_revision: Union[str, Sequence[str], None] = '86e9b290086b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('display_name', sa.String(), server_default='Unknown User', nullable=False))
    op.add_column('user_profiles', sa.Column('username', sa.String(), server_default='unknown_user', nullable=False))
    op.create_index(op.f('ix_user_profiles_display_name'), 'user_profiles', ['display_name'], unique=False)
    op.create_index(op.f('ix_user_profiles_username'), 'user_profiles', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_username'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_display_name'), table_name='user_profiles')
    op.drop_column('user_profiles', 'username')
    op.drop_column('user_profiles', 'display_name')
    # ### end Alembic commands ###
