"""Add llm model fields to global and bot settings

Revision ID: 65bbf3afc4fe
Revises: 45bed9133b24
Create Date: 2025-08-11 22:20:09.720482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65bbf3afc4fe'
down_revision: Union[str, Sequence[str], None] = '45bed9133b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # On ajoute la colonne en spécifiant un server_default pour que la migration
    # fonctionne sur les tables contenant déjà des données.
    op.add_column('global_settings', sa.Column('default_llm_model', sa.String(), nullable=False, server_default='llama3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'default_llm_model')
    # ### end Alembic commands ###