#### Fichier : app/alembic/versions/793eb6a56ac3_add_personality_field_to_bot_model.py
"""Add personality field to Bot model

Revision ID: 793eb6a56ac3
Revises: b65e86914beb
Create Date: 2025-09-26 20:15:52.978755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793eb6a56ac3'
down_revision: Union[str, Sequence[str], None] = 'b65e86914beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # --- MODIFICATION: Ajout de server_default pour gérer les lignes existantes ---
    op.add_column('bots', sa.Column('personality', sa.Text(), nullable=False, server_default='You are a helpful AI assistant.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'personality')
    # ### end Alembic commands ###