"""Add history limits to Bot model

Revision ID: 8672cb190ff2
Revises: 0069a27a1a6c
Create Date: 2025-09-07 09:28:32.132333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8672cb190ff2'
down_revision: Union[str, Sequence[str], None] = '0069a27a1a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('gatekeeper_history_limit', sa.Integer(), server_default='5', nullable=False))
    op.add_column('bots', sa.Column('conversation_history_limit', sa.Integer(), server_default='15', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'conversation_history_limit')
    op.drop_column('bots', 'gatekeeper_history_limit')
    # ### end Alembic commands ###
