"""Add UserProfile and UserNote tables

Revision ID: 86e9b290086b
Revises: ac3c37916a8c
Create Date: 2025-08-30 09:35:58.324662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86e9b290086b'
down_revision: Union[str, Sequence[str], None] = 'ac3c37916a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('server_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('author_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('note_content', sa.Text(), nullable=False),
    sa.Column('reliability_score', sa.Integer(), server_default='50', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('reliability_score >= 0 AND reliability_score <= 100', name='reliability_score_check'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notes_author_discord_id'), 'user_notes', ['author_discord_id'], unique=False)
    op.create_index(op.f('ix_user_notes_bot_id'), 'user_notes', ['bot_id'], unique=False)
    op.create_index(op.f('ix_user_notes_id'), 'user_notes', ['id'], unique=False)
    op.create_index(op.f('ix_user_notes_server_discord_id'), 'user_notes', ['server_discord_id'], unique=False)
    op.create_index(op.f('ix_user_notes_user_discord_id'), 'user_notes', ['user_discord_id'], unique=False)
    op.add_column('user_profiles', sa.Column('server_discord_id', sa.BigInteger(), nullable=False))
    op.add_column('user_profiles', sa.Column('behavioral_instructions', sa.Text(), server_default='Interact with the user normally.', nullable=False))
    op.alter_column('user_profiles', 'discord_user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using='discord_user_id::bigint')
    op.create_unique_constraint('_user_server_bot_uc', 'user_profiles', ['discord_user_id', 'server_discord_id', 'bot_id'])
    op.create_index(op.f('ix_user_profiles_bot_id'), 'user_profiles', ['bot_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_server_discord_id'), 'user_profiles', ['server_discord_id'], unique=False)
    op.drop_column('user_profiles', 'aliases')
    op.drop_column('user_profiles', 'profile_summary')
    op.drop_column('user_profiles', 'display_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_profiles', sa.Column('profile_summary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('aliases', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_profiles_server_discord_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_bot_id'), table_name='user_profiles')
    op.drop_constraint('_user_server_bot_uc', 'user_profiles', type_='unique')
    op.alter_column('user_profiles', 'discord_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('user_profiles', 'behavioral_instructions')
    op.drop_column('user_profiles', 'server_discord_id')
    op.drop_index(op.f('ix_user_notes_user_discord_id'), table_name='user_notes')
    op.drop_index(op.f('ix_user_notes_server_discord_id'), table_name='user_notes')
    op.drop_index(op.f('ix_user_notes_id'), table_name='user_notes')
    op.drop_index(op.f('ix_user_notes_bot_id'), table_name='user_notes')
    op.drop_index(op.f('ix_user_notes_author_discord_id'), table_name='user_notes')
    op.drop_table('user_notes')
    # ### end Alembic commands ###