"""Make discord_token in bots table optional

Revision ID: a181d2012660
Revises: 6581499b88e4
Create Date: 2025-09-05 23:25:50.298913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a181d2012660'
down_revision: Union[str, Sequence[str], None] = '6581499b88e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bots', 'discord_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bots', 'discord_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
