"""Add configuration column to bot_mcp_server_association table

Revision ID: ac3c37916a8c
Revises: 2d5ed58c9588
Create Date: 2025-08-21 15:39:12.045878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3c37916a8c'
down_revision: Union[str, Sequence[str], None] = '2d5ed58c9588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_mcp_server_association', sa.Column('configuration', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_mcp_server_association', 'configuration')
    # ### end Alembic commands ###
