"""add llm api key fields

Revision ID: add_llm_api_key_fields
Revises: 
Create Date: 2025-01-09 14:30:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_llm_api_key_fields'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add API key columns to global_settings table
    op.add_column('global_settings', sa.Column('decisional_llm_api_key', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('tools_llm_api_key', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('output_client_llm_api_key', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('multimodal_llm_api_key', sa.String(), nullable=True))
    
    # Add API key columns to bots table
    op.add_column('bots', sa.Column('decisional_llm_api_key', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('tools_llm_api_key', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('output_client_llm_api_key', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('multimodal_llm_api_key', sa.String(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove API key columns from bots table
    op.drop_column('bots', 'multimodal_llm_api_key')
    op.drop_column('bots', 'output_client_llm_api_key')
    op.drop_column('bots', 'tools_llm_api_key')
    op.drop_column('bots', 'decisional_llm_api_key')
    
    # Remove API key columns from global_settings table
    op.drop_column('global_settings', 'multimodal_llm_api_key')
    op.drop_column('global_settings', 'output_client_llm_api_key')
    op.drop_column('global_settings', 'tools_llm_api_key')
    op.drop_column('global_settings', 'decisional_llm_api_key')
    
    # ### end Alembic commands ###