"""Add tool prompt structure fields to global settings

Revision ID: d8538348e815
Revises: 45db25495b7f
Create Date: 2025-08-13 21:40:09.877984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8538348e815'
down_revision: Union[str, Sequence[str], None] = '45db25495b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('tools_system_prompt_header', sa.Text(), nullable=False, server_default='Default Header - Please Update'))
    op.add_column('global_settings', sa.Column('tools_system_prompt_example', sa.Text(), nullable=False, server_default='Default Example - Please Update'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'tools_system_prompt_example')
    op.drop_column('global_settings', 'tools_system_prompt_header')
    # ### end Alembic commands ###