"""Add discovered_tools_schema to MCPServer

Revision ID: db3c3b19f583
Revises: fff567bb9578
Create Date: 2025-10-05 19:48:21.589005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3c3b19f583'
down_revision: Union[str, Sequence[str], None] = 'fff567bb9578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('discovered_tools_schema', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_servers', 'discovered_tools_schema')
    # ### end Alembic commands ###
