"""Add ChannelSettings model

Revision ID: f963c9992c35
Revises: 947203bc539d
Create Date: 2025-10-24 07:56:48.833849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f963c9992c35'
down_revision: Union[str, Sequence[str], None] = '947203bc539d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('has_access', sa.Boolean(), nullable=False),
    sa.Column('passive_listening', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'channel_id', name='_bot_channel_uc')
    )
    op.create_index(op.f('ix_channel_settings_bot_id'), 'channel_settings', ['bot_id'], unique=False)
    op.create_index(op.f('ix_channel_settings_channel_id'), 'channel_settings', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_settings_channel_id'), table_name='channel_settings')
    op.drop_index(op.f('ix_channel_settings_bot_id'), table_name='channel_settings')
    op.drop_table('channel_settings')
    # ### end Alembic commands ###
